#!/bin/bash

# Now deprecated since I use background-color in hyprland directly 

# Start swww
if ! pgrep -x swww-daemon > /dev/null; then
    swww-daemon & disown
    sleep 0.5
fi

# Make bkg black
swww clear || true
